# application: nsitpercentage
# version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /(.+)
  script: main.app

- url: /
  static_files: percentage/index.html
  upload: percentage/index.html



libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"

